---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - namespace.ryio1010.github.io
  resources:
  - notifications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - namespace.ryio1010.github.io
  resources:
  - notifications/finalizers
  verbs:
  - update
- apiGroups:
  - namespace.ryio1010.github.io
  resources:
  - notifications/status
  verbs:
  - get
  - patch
  - update
